{
    'name': 'CEISA',
    'version': '1.0',
    'summary': 'Management Document CEISA',
    'author': 'Addon8',
    'category': 'Tools',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/ceisa_views.xml',
        'views/ceisa_40_views.xml',
        'views/ceisa_23_views.xml',
        'views/ceisa_config_views.xml',
        'data/ceisa_referensi_jenis_tpb_seed.xml',
        'data/ceisa_referensi_tujuan_pengiriman_seed.xml',
        'data/ceisa_referensi_kantor_pabean_seed.xml',
        'data/ceisa_referensi_dokumen_seed.xml',
        'data/ceisa_referensi_cara_angkut_seed.xml',
        'data/ceisa_referensi_negara_seed.xml',
        'data/ceisa_referensi_kemasan_seed.xml',
        'data/ceisa_referensi_ukuran_kontainer_seed.xml',
        'data/ceisa_referensi_jenis_kontainer_seed.xml',
        'data/ceisa_referensi_tipe_kontainer_seed.xml',
        'data/ceisa_referensi_satuan_seed.xml',
        'data/ceisa_referensi_fasilitas_tarif_seed.xml',
        'data/ceisa_company_master_seed.xml',
        'data/ceisa_referensi_jenis_identitas_seed.xml',
        'data/ceisa_numbering_master_seed.xml',
        'data/ceisa_referensi_pelabuhan_seed.xml',
        'data/ceisa_referensi_entitas_seed.xml',
        'data/ceisa_referensi_tutup_pu_seed.xml',
        'data/ceisa_referensi_tps_seed.xml',
        'data/ceisa_referensi_valuta_seed.xml',
        'data/ceisa_referensi_incoterm_seed.xml',
        'data/ceisa_referensi_asuransi_seed.xml',
        'data/ceisa_referensi_kena_pajak_seed.xml',
        'data/ceisa_referensi_kategori_barang_seed.xml',
        'data/ceisa_referensi_jenis_tarif_seed.xml',
        'data/ceisa_referensi_jenis_pungutan_seed.xml',
    ],
    'installable': True,
    'application': True,
}
